import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export const REPO_ROOT = path.resolve(__dirname, '../../..');
export const CONTENT_ROOT = path.join(REPO_ROOT, 'content/interpretations');
export const REVIEW_NOTES_ROOT = path.join(REPO_ROOT, 'content/review-notes');
export const GENERATED_ROOT = path.join(REPO_ROOT, 'src/lib/data/interpretations/generated');

export const SYNASTRY_FAMILIES = [
  ['conjunction', 'Conjunction'],
  ['opposition', 'Opposition'],
  ['trine', 'Trine'],
  ['square', 'Square'],
  ['sextile', 'Sextile'],
  ['quincunx', 'Quincunx'],
  ['angular-aspects', 'Angular'],
  ['minor-aspects', 'Minor']
];

export const TRANSIT_FAMILIES = [
  ['conjunction', 'Conjunction'],
  ['opposition', 'Opposition'],
  ['trine', 'Trine'],
  ['square', 'Square'],
  ['sextile', 'Sextile'],
  ['quincunx', 'Quincunx'],
  ['angular-aspects', 'Angular'],
  ['minor-aspects', 'Minor']
];

export const MAJOR_ASPECT_FAMILIES = ['Conjunction', 'Opposition', 'Trine', 'Square', 'Sextile'];

export const VALID_COMPATIBILITY = new Set(['harmonious', 'challenging', 'neutral']);
export const VALID_INTENSITY = new Set(['strong', 'moderate', 'weak']);
export const SYNASTRY_CONTEXTS = ['Interpretation', 'Romance', 'Friendship', 'Family', 'Business'];

export const GENERATED_WARNING = [
  '// This file is generated by scripts/interpretations/build.mjs.',
  '// Do not edit manually; edit content/interpretations markdown instead.'
].join('\n');
